title: LIB JESUS
author: @lefonseca
email: l.rodrigues.fonseca@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Base de conhecimento de Jesus (Leandro Fonseca), aqui servirá para 
  adicionar todo o conhecimento que tem aprendido em diversas frente de trabalho.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  @lefonseca

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
